apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drift-managed-low-severity
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: enhanced-low-app
      labels:
        drift-severity: low
        auto-remediate: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: enhanced-low-severity
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drift-managed-medium-severity
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: enhanced-medium-app
      labels:
        drift-severity: medium
        auto-remediate: conditional
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: enhanced-medium-severity
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drift-managed-high-severity
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: enhanced-high-app
      labels:
        drift-severity: high
        auto-remediate: immediate
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: enhanced-high-severity
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true