apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drift-managed-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - severity: "low"
        namespace: "enhanced-low-severity"
        autoRemediate: "true"
        enableAutomated: "true"
      - severity: "high"
        namespace: "enhanced-high-severity"
        autoRemediate: "immediate"
        enableAutomated: "true"
  template:
    metadata:
      name: 'enhanced-{{.severity}}-app'
      labels:
        drift-severity: '{{.severity}}'
        auto-remediate: '{{.autoRemediate}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/shibicr93/argo-drift-demo.git
        targetRevision: HEAD
        path: 'k8s/sample-apps/{{.severity}}-severity-manifests'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drift-managed-applicationset-manual
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - severity: "medium"
        namespace: "enhanced-medium-severity"
        autoRemediate: "conditional"
        enableAutomated: "false"
  template:
    metadata:
      name: 'enhanced-{{.severity}}-app'
      labels:
        drift-severity: '{{.severity}}'
        auto-remediate: '{{.autoRemediate}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/shibicr93/argo-drift-demo.git
        targetRevision: HEAD
        path: 'k8s/sample-apps/{{.severity}}-severity-manifests'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true