apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-drift-controller
  namespace: argocd
  labels:
    app: argo-drift-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-drift-controller
  template:
    metadata:
      labels:
        app: argo-drift-controller
    spec:
      serviceAccountName: argo-drift-controller
      containers:
      - name: drift-controller
        image: argo-drift-controller:latest
        imagePullPolicy: Never
        env:
        - name: DEMO_MODE
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

