apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: argocd
data:
  config.yaml: |
    channels:
      slack:
        webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#drift-alerts"
        username: "ArgoCD Drift Bot"
      email:
        smtp_server: "smtp.company.com"
        smtp_port: 587
        from_address: "argocd-alerts@company.com"
        to_addresses: ["devops@company.com", "sre@company.com"]
      pagerduty:
        integration_key: "YOUR_PAGERDUTY_INTEGRATION_KEY"
        service_id: "PXXXXX"
    
    templates:
      drift_detected: |
        🚨 Configuration Drift Detected
        Application: {{.app_name}}
        Severity: {{.severity}}
        Namespace: {{.namespace}}
        Action: {{.recommended_action}}
        
      remediation_complete: |
        ✅ Drift Remediation Complete
        Application: {{.app_name}}
        Action Taken: {{.action}}
        Status: {{.status}}
        Duration: {{.duration}}

